/**
 * Seed data for 20+ popular EVs.
 * All efficiency values in Wh/km.
 * Charging times in minutes.
 */

import {Vehicle, ConnectorType} from '../types';

type SeedVehicle = Omit<Vehicle, 'id'>;

export const SEED_VEHICLES: SeedVehicle[] = [
  // ── Tesla ──────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Tesla',
    brand: 'Tesla',
    model: 'Model 3',
    trim: 'Long Range RWD',
    modelYear: 2024,
    usableCapacityKwh: 75,
    wltpRangeKm: 629,
    epaRangeKm: 576,
    cltcRangeKm: null,
    manufacturerRangeKm: 629,
    realWorldMixedRangeKm: 500,
    realWorldHighwayRangeKm: 430,
    realWorldCityRangeKm: 570,
    efficiencyMixedWhPerKm: 150,
    efficiencyHighwayWhPerKm: 174,
    efficiencyCityWhPerKm: 132,
    maxAcChargingKw: 11,
    acConnectorType: 'NACS',
    maxDcChargingKw: 250,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 25,
    chargingTime20To80Min: 20,
    chargingTime0To100Min: 60,
    acFullChargeTimeMin: 460,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null,
    logoUrl: null,
    driveType: 'RWD',
    bodyStyle: 'Sedan',
    vinPrefix: '5YJ3', generation: null,
    grossCapacityKwh: 82, batteryChemistry: 'NMC', nominalVoltageV: 360, moduleCount: null, cellCount: null,
    peakDcChargingKw: 250, chargingCurve: null,
    lengthMm: 4720, widthMm: 1849, heightMm: 1443, wheelbaseMm: 2875, groundClearanceMm: 140,
    topSpeedKmh: 233, powerKw: 239, torqueNm: 420, zeroTo100Sec: 4.4,
    curbWeightKg: 1844, gvwrKg: 2232,
    coldWeatherEfficiencyMultiplier: 0.78, hotWeatherEfficiencyMultiplier: 0.95,
    lastUpdated: '2024-01-01', dataSource: 'Tesla.com', notes: null,
  },
  {
    manufacturer: 'Tesla',
    brand: 'Tesla',
    model: 'Model Y',
    trim: 'Long Range AWD',
    modelYear: 2024,
    usableCapacityKwh: 75,
    wltpRangeKm: 533,
    epaRangeKm: 514,
    cltcRangeKm: null,
    manufacturerRangeKm: 533,
    realWorldMixedRangeKm: 430,
    realWorldHighwayRangeKm: 380,
    realWorldCityRangeKm: 490,
    efficiencyMixedWhPerKm: 174,
    efficiencyHighwayWhPerKm: 197,
    efficiencyCityWhPerKm: 153,
    maxAcChargingKw: 11,
    acConnectorType: 'NACS',
    maxDcChargingKw: 250,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 28,
    chargingTime20To80Min: 22,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 460,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: '7SA', generation: null,
    grossCapacityKwh: 82, batteryChemistry: 'NMC', nominalVoltageV: 360, moduleCount: null, cellCount: null,
    peakDcChargingKw: 250, chargingCurve: null,
    lengthMm: 4751, widthMm: 1921, heightMm: 1624, wheelbaseMm: 2890, groundClearanceMm: 167,
    topSpeedKmh: 217, powerKw: 393, torqueNm: 559, zeroTo100Sec: 5.0,
    curbWeightKg: 2003, gvwrKg: 2580,
    coldWeatherEfficiencyMultiplier: 0.77, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Tesla.com', notes: null,
  },
  {
    manufacturer: 'Tesla',
    brand: 'Tesla',
    model: 'Model S',
    trim: 'Long Range',
    modelYear: 2024,
    usableCapacityKwh: 95,
    wltpRangeKm: 652,
    epaRangeKm: 652,
    cltcRangeKm: null,
    manufacturerRangeKm: 652,
    realWorldMixedRangeKm: 530,
    realWorldHighwayRangeKm: 470,
    realWorldCityRangeKm: 600,
    efficiencyMixedWhPerKm: 179,
    efficiencyHighwayWhPerKm: 202,
    efficiencyCityWhPerKm: 158,
    maxAcChargingKw: 11,
    acConnectorType: 'NACS',
    maxDcChargingKw: 250,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 20,
    chargingTime20To80Min: 15,
    chargingTime0To100Min: 55,
    acFullChargeTimeMin: 540,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: '5YJ', generation: null,
    grossCapacityKwh: 100, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 250, chargingCurve: null,
    lengthMm: 4979, widthMm: 1964, heightMm: 1445, wheelbaseMm: 2960, groundClearanceMm: 149,
    topSpeedKmh: 250, powerKw: 493, torqueNm: 670, zeroTo100Sec: 3.2,
    curbWeightKg: 2215, gvwrKg: 2722,
    coldWeatherEfficiencyMultiplier: 0.76, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Tesla.com', notes: null,
  },

  // ── Volkswagen ─────────────────────────────────────────────────────────────
  {
    manufacturer: 'Volkswagen',
    brand: 'Volkswagen',
    model: 'ID.4',
    trim: 'Pro 77 kWh',
    modelYear: 2024,
    usableCapacityKwh: 77,
    wltpRangeKm: 522,
    epaRangeKm: 402,
    cltcRangeKm: null,
    manufacturerRangeKm: 522,
    realWorldMixedRangeKm: 380,
    realWorldHighwayRangeKm: 320,
    realWorldCityRangeKm: 450,
    efficiencyMixedWhPerKm: 203,
    efficiencyHighwayWhPerKm: 241,
    efficiencyCityWhPerKm: 171,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 135,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 28,
    chargingTime20To80Min: 22,
    chargingTime0To100Min: 120,
    acFullChargeTimeMin: 480,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'RWD', bodyStyle: 'SUV', vinPrefix: 'WVG', generation: null,
    grossCapacityKwh: 82, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 135, chargingCurve: null,
    lengthMm: 4584, widthMm: 1852, heightMm: 1640, wheelbaseMm: 2766, groundClearanceMm: 163,
    topSpeedKmh: 160, powerKw: 150, torqueNm: 310, zeroTo100Sec: 8.5,
    curbWeightKg: 2109, gvwrKg: 2620,
    coldWeatherEfficiencyMultiplier: 0.72, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'VW.com', notes: null,
  },
  {
    manufacturer: 'Volkswagen',
    brand: 'Volkswagen',
    model: 'ID.3',
    trim: 'Pro S 82 kWh',
    modelYear: 2024,
    usableCapacityKwh: 79,
    wltpRangeKm: 548,
    epaRangeKm: null,
    cltcRangeKm: null,
    manufacturerRangeKm: 548,
    realWorldMixedRangeKm: 400,
    realWorldHighwayRangeKm: 330,
    realWorldCityRangeKm: 470,
    efficiencyMixedWhPerKm: 197,
    efficiencyHighwayWhPerKm: 239,
    efficiencyCityWhPerKm: 168,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 170,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 26,
    chargingTime20To80Min: 20,
    chargingTime0To100Min: 110,
    acFullChargeTimeMin: 480,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'RWD', bodyStyle: 'Hatchback', vinPrefix: null, generation: null,
    grossCapacityKwh: 82, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 170, chargingCurve: null,
    lengthMm: 4261, widthMm: 1809, heightMm: 1564, wheelbaseMm: 2771, groundClearanceMm: 154,
    topSpeedKmh: 160, powerKw: 150, torqueNm: 310, zeroTo100Sec: 7.9,
    curbWeightKg: 1832, gvwrKg: 2270,
    coldWeatherEfficiencyMultiplier: 0.72, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'VW.com', notes: null,
  },

  // ── Hyundai ────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Hyundai',
    brand: 'Hyundai',
    model: 'IONIQ 6',
    trim: 'Long Range RWD',
    modelYear: 2024,
    usableCapacityKwh: 77.4,
    wltpRangeKm: 614,
    epaRangeKm: 585,
    cltcRangeKm: null,
    manufacturerRangeKm: 614,
    realWorldMixedRangeKm: 510,
    realWorldHighwayRangeKm: 440,
    realWorldCityRangeKm: 580,
    efficiencyMixedWhPerKm: 152,
    efficiencyHighwayWhPerKm: 176,
    efficiencyCityWhPerKm: 133,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 233,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 18,
    chargingTime20To80Min: 14,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 420,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'RWD', bodyStyle: 'Sedan', vinPrefix: 'KMH', generation: null,
    grossCapacityKwh: 84, batteryChemistry: 'NMC', nominalVoltageV: 800, moduleCount: null, cellCount: null,
    peakDcChargingKw: 233, chargingCurve: null,
    lengthMm: 4855, widthMm: 1880, heightMm: 1495, wheelbaseMm: 2950, groundClearanceMm: 140,
    topSpeedKmh: 185, powerKw: 168, torqueNm: 350, zeroTo100Sec: 7.4,
    curbWeightKg: 1985, gvwrKg: 2495,
    coldWeatherEfficiencyMultiplier: 0.75, hotWeatherEfficiencyMultiplier: 0.95,
    lastUpdated: '2024-01-01', dataSource: 'Hyundai.com', notes: null,
  },
  {
    manufacturer: 'Hyundai',
    brand: 'Hyundai',
    model: 'IONIQ 5',
    trim: 'Long Range AWD',
    modelYear: 2024,
    usableCapacityKwh: 74,
    wltpRangeKm: 481,
    epaRangeKm: 430,
    cltcRangeKm: null,
    manufacturerRangeKm: 481,
    realWorldMixedRangeKm: 380,
    realWorldHighwayRangeKm: 330,
    realWorldCityRangeKm: 440,
    efficiencyMixedWhPerKm: 195,
    efficiencyHighwayWhPerKm: 224,
    efficiencyCityWhPerKm: 168,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 233,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 18,
    chargingTime20To80Min: 14,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 420,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: 'KMH', generation: null,
    grossCapacityKwh: 84, batteryChemistry: 'NMC', nominalVoltageV: 800, moduleCount: null, cellCount: null,
    peakDcChargingKw: 233, chargingCurve: null,
    lengthMm: 4635, widthMm: 1890, heightMm: 1645, wheelbaseMm: 3000, groundClearanceMm: 160,
    topSpeedKmh: 185, powerKw: 225, torqueNm: 605, zeroTo100Sec: 5.1,
    curbWeightKg: 2114, gvwrKg: 2680,
    coldWeatherEfficiencyMultiplier: 0.74, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Hyundai.com', notes: null,
  },

  // ── Kia ────────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Kia',
    brand: 'Kia',
    model: 'EV6',
    trim: 'Long Range AWD',
    modelYear: 2024,
    usableCapacityKwh: 74,
    wltpRangeKm: 484,
    epaRangeKm: 435,
    cltcRangeKm: null,
    manufacturerRangeKm: 484,
    realWorldMixedRangeKm: 380,
    realWorldHighwayRangeKm: 330,
    realWorldCityRangeKm: 440,
    efficiencyMixedWhPerKm: 195,
    efficiencyHighwayWhPerKm: 224,
    efficiencyCityWhPerKm: 168,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 233,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 18,
    chargingTime20To80Min: 14,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 420,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Crossover', vinPrefix: 'KNA', generation: null,
    grossCapacityKwh: 84, batteryChemistry: 'NMC', nominalVoltageV: 800, moduleCount: null, cellCount: null,
    peakDcChargingKw: 233, chargingCurve: null,
    lengthMm: 4695, widthMm: 1890, heightMm: 1550, wheelbaseMm: 2900, groundClearanceMm: 160,
    topSpeedKmh: 188, powerKw: 239, torqueNm: 605, zeroTo100Sec: 5.1,
    curbWeightKg: 2054, gvwrKg: 2630,
    coldWeatherEfficiencyMultiplier: 0.74, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Kia.com', notes: null,
  },

  // ── BMW ────────────────────────────────────────────────────────────────────
  {
    manufacturer: 'BMW',
    brand: 'BMW',
    model: 'iX',
    trim: 'xDrive50',
    modelYear: 2024,
    usableCapacityKwh: 105.2,
    wltpRangeKm: 630,
    epaRangeKm: 547,
    cltcRangeKm: null,
    manufacturerRangeKm: 630,
    realWorldMixedRangeKm: 490,
    realWorldHighwayRangeKm: 410,
    realWorldCityRangeKm: 570,
    efficiencyMixedWhPerKm: 215,
    efficiencyHighwayWhPerKm: 256,
    efficiencyCityWhPerKm: 184,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 200,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 35,
    chargingTime20To80Min: 28,
    chargingTime0To100Min: 90,
    acFullChargeTimeMin: 600,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: 'WBA', generation: null,
    grossCapacityKwh: 111.5, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 200, chargingCurve: null,
    lengthMm: 4953, widthMm: 1967, heightMm: 1696, wheelbaseMm: 3000, groundClearanceMm: 203,
    topSpeedKmh: 200, powerKw: 385, torqueNm: 765, zeroTo100Sec: 4.6,
    curbWeightKg: 2585, gvwrKg: 3130,
    coldWeatherEfficiencyMultiplier: 0.73, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'BMW.com', notes: null,
  },
  {
    manufacturer: 'BMW',
    brand: 'BMW',
    model: 'i4',
    trim: 'M50 xDrive',
    modelYear: 2024,
    usableCapacityKwh: 80.7,
    wltpRangeKm: 521,
    epaRangeKm: 422,
    cltcRangeKm: null,
    manufacturerRangeKm: 521,
    realWorldMixedRangeKm: 390,
    realWorldHighwayRangeKm: 330,
    realWorldCityRangeKm: 460,
    efficiencyMixedWhPerKm: 207,
    efficiencyHighwayWhPerKm: 245,
    efficiencyCityWhPerKm: 175,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 205,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 31,
    chargingTime20To80Min: 25,
    chargingTime0To100Min: 80,
    acFullChargeTimeMin: 480,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: 'WBA', generation: null,
    grossCapacityKwh: 83.9, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 205, chargingCurve: null,
    lengthMm: 4783, widthMm: 1852, heightMm: 1448, wheelbaseMm: 2856, groundClearanceMm: 130,
    topSpeedKmh: 225, powerKw: 400, torqueNm: 795, zeroTo100Sec: 3.9,
    curbWeightKg: 2215, gvwrKg: 2745,
    coldWeatherEfficiencyMultiplier: 0.74, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'BMW.com', notes: null,
  },

  // ── Mercedes ───────────────────────────────────────────────────────────────
  {
    manufacturer: 'Mercedes-Benz',
    brand: 'Mercedes-Benz',
    model: 'EQS',
    trim: '450+',
    modelYear: 2024,
    usableCapacityKwh: 107.8,
    wltpRangeKm: 783,
    epaRangeKm: 660,
    cltcRangeKm: null,
    manufacturerRangeKm: 783,
    realWorldMixedRangeKm: 600,
    realWorldHighwayRangeKm: 510,
    realWorldCityRangeKm: 690,
    efficiencyMixedWhPerKm: 180,
    efficiencyHighwayWhPerKm: 211,
    efficiencyCityWhPerKm: 156,
    maxAcChargingKw: 22,
    acConnectorType: 'Type2',
    maxDcChargingKw: 200,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 31,
    chargingTime20To80Min: 25,
    chargingTime0To100Min: 80,
    acFullChargeTimeMin: 300,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'RWD', bodyStyle: 'Sedan', vinPrefix: 'W1K', generation: null,
    grossCapacityKwh: 120, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 200, chargingCurve: null,
    lengthMm: 5216, widthMm: 1926, heightMm: 1512, wheelbaseMm: 3210, groundClearanceMm: 125,
    topSpeedKmh: 210, powerKw: 245, torqueNm: 568, zeroTo100Sec: 6.2,
    curbWeightKg: 2585, gvwrKg: 3075,
    coldWeatherEfficiencyMultiplier: 0.74, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Mercedes.com', notes: null,
  },

  // ── Audi ───────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Audi',
    brand: 'Audi',
    model: 'Q8 e-tron',
    trim: '55 quattro',
    modelYear: 2024,
    usableCapacityKwh: 106,
    wltpRangeKm: 582,
    epaRangeKm: 487,
    cltcRangeKm: null,
    manufacturerRangeKm: 582,
    realWorldMixedRangeKm: 450,
    realWorldHighwayRangeKm: 380,
    realWorldCityRangeKm: 520,
    efficiencyMixedWhPerKm: 236,
    efficiencyHighwayWhPerKm: 279,
    efficiencyCityWhPerKm: 204,
    maxAcChargingKw: 22,
    acConnectorType: 'Type2',
    maxDcChargingKw: 170,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 31,
    chargingTime20To80Min: 25,
    chargingTime0To100Min: 100,
    acFullChargeTimeMin: 300,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: 'WA1', generation: null,
    grossCapacityKwh: 114, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 170, chargingCurve: null,
    lengthMm: 4915, widthMm: 1935, heightMm: 1619, wheelbaseMm: 2928, groundClearanceMm: 175,
    topSpeedKmh: 200, powerKw: 300, torqueNm: 664, zeroTo100Sec: 5.6,
    curbWeightKg: 2610, gvwrKg: 3230,
    coldWeatherEfficiencyMultiplier: 0.72, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'Audi.com', notes: null,
  },

  // ── Porsche ────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Porsche',
    brand: 'Porsche',
    model: 'Taycan',
    trim: 'Long Range',
    modelYear: 2024,
    usableCapacityKwh: 93.4,
    wltpRangeKm: 631,
    epaRangeKm: null,
    cltcRangeKm: null,
    manufacturerRangeKm: 631,
    realWorldMixedRangeKm: 490,
    realWorldHighwayRangeKm: 410,
    realWorldCityRangeKm: 570,
    efficiencyMixedWhPerKm: 191,
    efficiencyHighwayWhPerKm: 228,
    efficiencyCityWhPerKm: 164,
    maxAcChargingKw: 22,
    acConnectorType: 'Type2',
    maxDcChargingKw: 320,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 18,
    chargingTime20To80Min: 14,
    chargingTime0To100Min: 55,
    acFullChargeTimeMin: 270,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'RWD', bodyStyle: 'Sedan', vinPrefix: 'WP0', generation: null,
    grossCapacityKwh: 105, batteryChemistry: 'NMC', nominalVoltageV: 800, moduleCount: null, cellCount: null,
    peakDcChargingKw: 320, chargingCurve: null,
    lengthMm: 4963, widthMm: 1966, heightMm: 1379, wheelbaseMm: 2900, groundClearanceMm: 128,
    topSpeedKmh: 230, powerKw: 300, torqueNm: 345, zeroTo100Sec: 5.4,
    curbWeightKg: 2320, gvwrKg: 2855,
    coldWeatherEfficiencyMultiplier: 0.75, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Porsche.com', notes: null,
  },

  // ── Rivian ─────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Rivian',
    brand: 'Rivian',
    model: 'R1T',
    trim: 'Dual Motor Large Pack',
    modelYear: 2024,
    usableCapacityKwh: 135,
    wltpRangeKm: null,
    epaRangeKm: 515,
    cltcRangeKm: null,
    manufacturerRangeKm: 515,
    realWorldMixedRangeKm: 430,
    realWorldHighwayRangeKm: 360,
    realWorldCityRangeKm: 500,
    efficiencyMixedWhPerKm: 314,
    efficiencyHighwayWhPerKm: 375,
    efficiencyCityWhPerKm: 270,
    maxAcChargingKw: 11.5,
    acConnectorType: 'NACS',
    maxDcChargingKw: 220,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 37,
    chargingTime20To80Min: 29,
    chargingTime0To100Min: 100,
    acFullChargeTimeMin: 720,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Pickup', vinPrefix: '7FCTS', generation: null,
    grossCapacityKwh: 149, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 220, chargingCurve: null,
    lengthMm: 5487, widthMm: 1986, heightMm: 1803, wheelbaseMm: 3454, groundClearanceMm: 354,
    topSpeedKmh: 177, powerKw: 522, torqueNm: 1124, zeroTo100Sec: 3.5,
    curbWeightKg: 3110, gvwrKg: 3946,
    coldWeatherEfficiencyMultiplier: 0.70, hotWeatherEfficiencyMultiplier: 0.92,
    lastUpdated: '2024-01-01', dataSource: 'Rivian.com', notes: null,
  },

  // ── Ford ───────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Ford',
    brand: 'Ford',
    model: 'Mustang Mach-E',
    trim: 'Extended Range AWD',
    modelYear: 2024,
    usableCapacityKwh: 88,
    wltpRangeKm: 490,
    epaRangeKm: 446,
    cltcRangeKm: null,
    manufacturerRangeKm: 490,
    realWorldMixedRangeKm: 390,
    realWorldHighwayRangeKm: 330,
    realWorldCityRangeKm: 450,
    efficiencyMixedWhPerKm: 226,
    efficiencyHighwayWhPerKm: 267,
    efficiencyCityWhPerKm: 196,
    maxAcChargingKw: 11,
    acConnectorType: 'NACS',
    maxDcChargingKw: 150,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 38,
    chargingTime20To80Min: 30,
    chargingTime0To100Min: 110,
    acFullChargeTimeMin: 480,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: '3FMTK', generation: null,
    grossCapacityKwh: 91, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 150, chargingCurve: null,
    lengthMm: 4713, widthMm: 1881, heightMm: 1600, wheelbaseMm: 2764, groundClearanceMm: 178,
    topSpeedKmh: 180, powerKw: 258, torqueNm: 580, zeroTo100Sec: 5.1,
    curbWeightKg: 2218, gvwrKg: 2806,
    coldWeatherEfficiencyMultiplier: 0.72, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'Ford.com', notes: null,
  },
  {
    manufacturer: 'Ford',
    brand: 'Ford',
    model: 'F-150 Lightning',
    trim: 'Extended Range',
    modelYear: 2024,
    usableCapacityKwh: 131,
    wltpRangeKm: null,
    epaRangeKm: 515,
    cltcRangeKm: null,
    manufacturerRangeKm: 515,
    realWorldMixedRangeKm: 420,
    realWorldHighwayRangeKm: 350,
    realWorldCityRangeKm: 490,
    efficiencyMixedWhPerKm: 312,
    efficiencyHighwayWhPerKm: 374,
    efficiencyCityWhPerKm: 267,
    maxAcChargingKw: 19.2,
    acConnectorType: 'NACS',
    maxDcChargingKw: 150,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 44,
    chargingTime20To80Min: 35,
    chargingTime0To100Min: 120,
    acFullChargeTimeMin: 420,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Pickup', vinPrefix: '1FTBW', generation: null,
    grossCapacityKwh: 145, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 150, chargingCurve: null,
    lengthMm: 5915, widthMm: 2029, heightMm: 1955, wheelbaseMm: 3683, groundClearanceMm: 240,
    topSpeedKmh: 168, powerKw: 433, torqueNm: 1050, zeroTo100Sec: 4.0,
    curbWeightKg: 3220, gvwrKg: 4309,
    coldWeatherEfficiencyMultiplier: 0.68, hotWeatherEfficiencyMultiplier: 0.91,
    lastUpdated: '2024-01-01', dataSource: 'Ford.com', notes: null,
  },

  // ── BYD ───────────────────────────────────────────────────────────────────
  {
    manufacturer: 'BYD',
    brand: 'BYD',
    model: 'Seal',
    trim: 'AWD',
    modelYear: 2024,
    usableCapacityKwh: 82.5,
    wltpRangeKm: 520,
    epaRangeKm: null,
    cltcRangeKm: 650,
    manufacturerRangeKm: 650,
    realWorldMixedRangeKm: 430,
    realWorldHighwayRangeKm: 360,
    realWorldCityRangeKm: 500,
    efficiencyMixedWhPerKm: 192,
    efficiencyHighwayWhPerKm: 229,
    efficiencyCityWhPerKm: 165,
    maxAcChargingKw: 11,
    acConnectorType: 'CCS2',
    maxDcChargingKw: 150,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 26,
    chargingTime20To80Min: 20,
    chargingTime0To100Min: 95,
    acFullChargeTimeMin: 480,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: null, generation: null,
    grossCapacityKwh: 87, batteryChemistry: 'LFP', nominalVoltageV: 570, moduleCount: null, cellCount: null,
    peakDcChargingKw: 150, chargingCurve: null,
    lengthMm: 4800, widthMm: 1875, heightMm: 1460, wheelbaseMm: 2920, groundClearanceMm: 150,
    topSpeedKmh: 180, powerKw: 390, torqueNm: 670, zeroTo100Sec: 3.8,
    curbWeightKg: 2150, gvwrKg: 2680,
    coldWeatherEfficiencyMultiplier: 0.80, hotWeatherEfficiencyMultiplier: 0.97,
    lastUpdated: '2024-01-01', dataSource: 'BYD.com', notes: null,
  },
  {
    manufacturer: 'BYD',
    brand: 'BYD',
    model: 'Atto 3',
    trim: 'Extended Range',
    modelYear: 2024,
    usableCapacityKwh: 60.48,
    wltpRangeKm: 420,
    epaRangeKm: null,
    cltcRangeKm: 510,
    manufacturerRangeKm: 510,
    realWorldMixedRangeKm: 340,
    realWorldHighwayRangeKm: 285,
    realWorldCityRangeKm: 400,
    efficiencyMixedWhPerKm: 178,
    efficiencyHighwayWhPerKm: 212,
    efficiencyCityWhPerKm: 151,
    maxAcChargingKw: 7,
    acConnectorType: 'CCS2',
    maxDcChargingKw: 80,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 38,
    chargingTime20To80Min: 30,
    chargingTime0To100Min: 135,
    acFullChargeTimeMin: 540,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'FWD', bodyStyle: 'SUV', vinPrefix: null, generation: null,
    grossCapacityKwh: 64.2, batteryChemistry: 'LFP', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 80, chargingCurve: null,
    lengthMm: 4455, widthMm: 1875, heightMm: 1615, wheelbaseMm: 2720, groundClearanceMm: 175,
    topSpeedKmh: 160, powerKw: 150, torqueNm: 310, zeroTo100Sec: 7.3,
    curbWeightKg: 1750, gvwrKg: 2240,
    coldWeatherEfficiencyMultiplier: 0.82, hotWeatherEfficiencyMultiplier: 0.97,
    lastUpdated: '2024-01-01', dataSource: 'BYD.com', notes: null,
  },

  // ── Volvo ──────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Volvo',
    brand: 'Volvo',
    model: 'EX90',
    trim: 'Twin Motor Performance',
    modelYear: 2024,
    usableCapacityKwh: 107,
    wltpRangeKm: 580,
    epaRangeKm: 475,
    cltcRangeKm: null,
    manufacturerRangeKm: 580,
    realWorldMixedRangeKm: 460,
    realWorldHighwayRangeKm: 390,
    realWorldCityRangeKm: 530,
    efficiencyMixedWhPerKm: 233,
    efficiencyHighwayWhPerKm: 274,
    efficiencyCityWhPerKm: 202,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 250,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 30,
    chargingTime20To80Min: 24,
    chargingTime0To100Min: 85,
    acFullChargeTimeMin: 570,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'SUV', vinPrefix: 'YV4', generation: null,
    grossCapacityKwh: 111, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 250, chargingCurve: null,
    lengthMm: 4953, widthMm: 1964, heightMm: 1744, wheelbaseMm: 2985, groundClearanceMm: 210,
    topSpeedKmh: 210, powerKw: 380, torqueNm: 910, zeroTo100Sec: 4.9,
    curbWeightKg: 2748, gvwrKg: 3330,
    coldWeatherEfficiencyMultiplier: 0.73, hotWeatherEfficiencyMultiplier: 0.93,
    lastUpdated: '2024-01-01', dataSource: 'Volvo.com', notes: null,
  },

  // ── Polestar ────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Polestar',
    brand: 'Polestar',
    model: 'Polestar 2',
    trim: 'Long Range Dual Motor',
    modelYear: 2024,
    usableCapacityKwh: 78,
    wltpRangeKm: 592,
    epaRangeKm: 483,
    cltcRangeKm: null,
    manufacturerRangeKm: 592,
    realWorldMixedRangeKm: 460,
    realWorldHighwayRangeKm: 390,
    realWorldCityRangeKm: 530,
    efficiencyMixedWhPerKm: 170,
    efficiencyHighwayWhPerKm: 200,
    efficiencyCityWhPerKm: 147,
    maxAcChargingKw: 11,
    acConnectorType: 'Type2',
    maxDcChargingKw: 205,
    dcConnectorType: 'CCS2',
    chargingTime10To80Min: 28,
    chargingTime20To80Min: 22,
    chargingTime0To100Min: 80,
    acFullChargeTimeMin: 420,
    supportedConnectors: ['CCS2', 'Type2'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: 'YV1', generation: null,
    grossCapacityKwh: 82, batteryChemistry: 'NMC', nominalVoltageV: 400, moduleCount: null, cellCount: null,
    peakDcChargingKw: 205, chargingCurve: null,
    lengthMm: 4606, widthMm: 1859, heightMm: 1479, wheelbaseMm: 2735, groundClearanceMm: 151,
    topSpeedKmh: 205, powerKw: 310, torqueNm: 740, zeroTo100Sec: 4.5,
    curbWeightKg: 2072, gvwrKg: 2570,
    coldWeatherEfficiencyMultiplier: 0.73, hotWeatherEfficiencyMultiplier: 0.94,
    lastUpdated: '2024-01-01', dataSource: 'Polestar.com', notes: null,
  },

  // ── NIO ────────────────────────────────────────────────────────────────────
  {
    manufacturer: 'NIO',
    brand: 'NIO',
    model: 'ET7',
    trim: '100 kWh',
    modelYear: 2024,
    usableCapacityKwh: 100,
    wltpRangeKm: 580,
    epaRangeKm: null,
    cltcRangeKm: 675,
    manufacturerRangeKm: 675,
    realWorldMixedRangeKm: 490,
    realWorldHighwayRangeKm: 410,
    realWorldCityRangeKm: 570,
    efficiencyMixedWhPerKm: 204,
    efficiencyHighwayWhPerKm: 244,
    efficiencyCityWhPerKm: 175,
    maxAcChargingKw: 11,
    acConnectorType: 'GB/T',
    maxDcChargingKw: 500,
    dcConnectorType: 'GB/T',
    chargingTime10To80Min: 20,
    chargingTime20To80Min: 16,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 540,
    supportedConnectors: ['GB/T'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: null, generation: null,
    grossCapacityKwh: 100, batteryChemistry: 'NMC', nominalVoltageV: 480, moduleCount: null, cellCount: null,
    peakDcChargingKw: 500, chargingCurve: null,
    lengthMm: 5098, widthMm: 1987, heightMm: 1505, wheelbaseMm: 3060, groundClearanceMm: 130,
    topSpeedKmh: 200, powerKw: 480, torqueNm: 850, zeroTo100Sec: 3.8,
    curbWeightKg: 2379, gvwrKg: 2929,
    coldWeatherEfficiencyMultiplier: 0.76, hotWeatherEfficiencyMultiplier: 0.95,
    lastUpdated: '2024-01-01', dataSource: 'NIO.com', notes: null,
  },

  // ── Lucid ──────────────────────────────────────────────────────────────────
  {
    manufacturer: 'Lucid',
    brand: 'Lucid',
    model: 'Air',
    trim: 'Grand Touring',
    modelYear: 2024,
    usableCapacityKwh: 112,
    wltpRangeKm: null,
    epaRangeKm: 756,
    cltcRangeKm: null,
    manufacturerRangeKm: 756,
    realWorldMixedRangeKm: 610,
    realWorldHighwayRangeKm: 520,
    realWorldCityRangeKm: 700,
    efficiencyMixedWhPerKm: 184,
    efficiencyHighwayWhPerKm: 215,
    efficiencyCityWhPerKm: 160,
    maxAcChargingKw: 19.2,
    acConnectorType: 'NACS',
    maxDcChargingKw: 300,
    dcConnectorType: 'NACS',
    chargingTime10To80Min: 22,
    chargingTime20To80Min: 17,
    chargingTime0To100Min: 65,
    acFullChargeTimeMin: 360,
    supportedConnectors: ['NACS', 'CCS1'],
    imageUrl: null, logoUrl: null,
    driveType: 'AWD', bodyStyle: 'Sedan', vinPrefix: 'L2CV', generation: null,
    grossCapacityKwh: 118, batteryChemistry: 'NMC', nominalVoltageV: 900, moduleCount: null, cellCount: null,
    peakDcChargingKw: 300, chargingCurve: null,
    lengthMm: 4975, widthMm: 1978, heightMm: 1411, wheelbaseMm: 2994, groundClearanceMm: 122,
    topSpeedKmh: 270, powerKw: 597, torqueNm: 900, zeroTo100Sec: 3.0,
    curbWeightKg: 2280, gvwrKg: 2880,
    coldWeatherEfficiencyMultiplier: 0.77, hotWeatherEfficiencyMultiplier: 0.95,
    lastUpdated: '2024-01-01', dataSource: 'LucidMotors.com', notes: null,
  },
];
